=== Naylepsh/UWr-II/2019-2020/Lato/DOTNET/List 2.4/XML/XML/data.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:MyValidator="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="MyData" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Students">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="Student">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Index" type="xs:unsignedInt" />
              <xs:element name="Name" type="xs:string" />
              <xs:element name="Surname" type="xs:string" />
              <xs:element name="BirthDate" type="xs:date" />
              <xs:element maxOccurs="unbounded" name="Address">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="City" type="xs:string" />
                    <xs:element name="Street" type="xs:string" />
                  </xs:sequence>
                  <xs:attribute name="type" type="xs:string" use="optional" />
                </xs:complexType>
              </xs:element>
              <xs:element name="Courses">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="Subject">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Name" type="xs:string" />
                          <xs:element name="Grade" type="xs:decimal" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Naylepsh/UWr-II/Term VI/dotNET/List 2.4/XML/XML/InvalidData.xml
<?xml version="1.0" encoding="utf-8" ?>
<Students xmlns="MyData" 
          xmlns:MyValidator='http://www.w3.org/2001/XMLSchema-instance' 
          MyValidator:schemaLocation='MyData data.xsd'>
<Student>
    <Name>John</Name>
    <Surname>Doe</Surname>
    <BirthDate>1990-11-10</BirthDate>
    <Address type="primary">
      <City>Cambridge</City>
      <Street>Ridge St</Street>
    </Address>
    <Address>
      <City>Cambridge</City>
      <Street>High St</Street>
    </Address>
    <Courses>
      <Subject>
        <Name>6.0001 Introduction to Computer Science and Programming in Python</Name>
        <Grade>3.0</Grade>
      </Subject>
      <Subject>
        <Name>6.0002 Introduction to Computational Thinking and Data Science</Name>
        <Grade>3.0</Grade>
      </Subject>
    </Courses>
  </Student>

  <Student>
    <Index>211234</Index>
    <Name>Jane</Name>
    <Surname>Doe</Surname>
    <BirthDate>1991-12-01</BirthDate>
    <Address type="primary">
      <City>Cambridge</City>
      <Street>Lockeland Rd</Street>
    </Address>
    <Address>
      <City>Los Angeles</City>
      <Street>Sawyer St</Street>
    </Address>
  </Student>
</Students>
